### ISSUE TITLE
PullPanel squeezes the tabbar everytime the it updates

### ISSUE THREAD

**Issue by ruhaim** [mgwt/mgwt#260] opened 2015-06-25 12:44 UTC
Initial appearance
![](http://i.imgur.com/XOzDaBB.png)

After several pull to refresh attempts
![](http://i.imgur.com/qQoxOn2.png)

**Comment by luxmar** [comment] 2015-06-25 13:49
duplicate of https://github.com/mgwt/mgwt/issues/255

**Comment by waynedyck** [comment] 2016-02-24 06:39
This has been fixed with the latest versions of Chrome.

**Closed by waynedyck** 2016-02-24 06:39 UTC
